#!/bin/sh

export KWIN_COMPOSE=O2ES
export GDK_BACKEND=x11

export LD_LIBRARY_PATH=/opt/usr/lib:/opt/usr/lib/aarch64-linux-gnu/
export QT_QPA_PLATFORM_PLUGIN_PATH=/opt/usr/plugins/platforms:/opt/usr/lib/aarch64-linux-gnu/plugins/platforms
export QT_PLUGIN_PATH=/opt/usr/plugins:/opt/usr/lib/aarch64-linux-gnu/plugins/
export QML2_IMPORT_PATH=/opt/usr/qml:/usr/lib/aarch64-linux-gnu/qt5/qml
export XDG_DATA_DIRS=/opt/usr/share:/usr/share
export LD_PRELOAD=/opt/usr/plugins/platforms/libdde-kwin-wayland.so

if [ ! -f "$HOME/.config/kglobalshortcutsrc" ]; then
    cp -n /etc/xdg/kglobalshortcutsrc $HOME/.config/kglobalshortcutsrc
fi

exec /opt/usr/bin/kwin_wayland -platform dde-kwin-wayland --xwayland --drm --no-lockscreen  startdde-wayland
