#!/bin/sh

export KWIN_COMPOSE=O2ES
export GDK_BACKEND=x11

export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/aarch64-linux-gnu/
export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/plugins/platforms:/usr/local/lib/aarch64-linux-gnu/plugins/platforms
export QT_PLUGIN_PATH=/usr/local/plugins:/usr/local/lib/aarch64-linux-gnu/plugins/
export QML2_IMPORT_PATH=/usr/local/qml:/usr/local/lib/aarch64-linux-gnu/qml:/usr/lib/aarch64-linux-gnu/qt5/qml
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/usr/local/etc/xdg:/etc/xdg
export LD_PRELOAD=/usr/local/plugins/platforms/libdde-kwin-wayland.so

if [ ! -f "$HOME/.config/kglobalshortcutsrc" ]; then
    cp -n /usr/local/etc/xdg/kglobalshortcutsrc $HOME/.config/kglobalshortcutsrc
fi

export QT_LOGGING_RULES="kwin*=true;kwin_libinput=false;"

res=`ps aux | grep /usr/local/bin/kwin_wayland  | awk '{print $8}' | grep R`
while [ $? -eq 0 ]
do
    sleep 0.5s
	res=`ps aux | grep /usr/local/bin/kwin_wayland | awk '{print $8}' | grep R`
done

exec /usr/local/bin/kwin_wayland -platform dde-kwin-wayland --xwayland --drm --no-lockscreen  startdde-wayland 2> $HOME/.kwin.log
