#!/usr/bin/bash
unset LD_LIBRARY_PATH 
unset QT_QPA_PLATFORM_PLUGIN_PATH 
unset QT_PLUGIN_PATH 
unset QML2_IMPORT_PATH
unset XDG_DATA_DIRS
export QT_QPA_PLATFORM=xcb
export DDE_DEBUG_LEVEL=debug

. "${HOME}/.dde_env"

exec dbus-launch /usr/bin/startdde
